name: torliga
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 

  # Routing
  go_router: ^8.0.1                
  # State Management 
  flutter_bloc: ^8.1.6             
  # UI Components
  buttons_tabbar: ^1.3.13                 
  flutter_svg: ^2.0.10                   
  cached_network_image: ^3.4.1 
  shimmer: ^3.0.0           
  # Connectivity
  connectivity_plus: ^6.1.0       
  # Logging
  logger: ^2.4.0
   # Functionality
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^1.0.0+1
  dio: ^5.7.0                 
  # Value Equality
  equatable: ^2.0.5                        
  # Service Locator
  get_it: ^8.0.2                   
  # JWT Handling
  jwt_decoder: ^2.0.1            
  # Google Fonts
  google_fonts: ^6.2.1  
  # Formatting dates, numbers etc...
  intl: ^0.19.0
  # Resizing of text
  auto_size_text: ^3.0.0
  
  web_socket_channel: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter                  
  flutter_lints: ^5.0.0           
flutter:
  uses-material-design: true
  assets:
    - assets/svg/                
    - assets/jpg/                 